### ISSUE TITLE
Is this package maintained? Still useful for modern Pyramid?

### ISSUE THREAD

**Issue by bjmc** [Pylons/pyramid_traversalwrapper#6]

**Comment by bjmc** [comment]
#5 Suggests it's no good for modern Pyramid.

**Comment by digitalresistor** [comment]
Is there a particular reason you are asking the question? Is there a problem you are trying to solve that you believe could be solved with this package but due to the changes made in Pyramid since no longer works?

**Comment by bjmc** [comment]
The reason I'm asking the question is that I wanted to use this package to automatically manage setting `__parent__` and `__name__` on the Resources in my Pyramid traversal tree. It's recommended in a [sidebar of the Pyramid 1.9.2 docs](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/resources.html#location-aware-resources) about location-aware resources.

I configured it via [the imperative method](http://pyramid-traversalwrapper.readthedocs.io/en/latest/#usage) but when I try to run my app, it just fails immediately:

```Traceback (most recent call last):
  File "/home/bjmc/Sandbox/myapp/globus/main/app.py", line 298, in __call__
    return self.application(environ, start_response)
  File "/home/bjmc/Sandbox/myapp/globus/main/request_id_middleware.py", line 24, in __call__
    return self.application(environ, custom_start_response)
  File "/home/bjmc/Sandbox/myapp/globus/main/app.py", line 331, in __call__
    return self.application(environ, start_response)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid/router.py", line 132, in handle_request
    tdict = traverser(request)
  File "/home/bjmc/.local/share/virtualenvs/myapp-hJBVVxkr/local/lib/python2.7/site-packages/pyramid_traversalwrapper/__init__.py", line 28, in __call__
    if 'bfg.routes.matchdict' in environ:
TypeError: argument of type 'WebRequest' is not iterable
```
Given that there's an outstanding pull request for compatibility with Pyramid v1.5, I guess I shouldn't be surprised it won't work with v1.9.

I was hoping maybe it had been superseded by another package, or similar functionality had been introduced in the main Pyramid framework.

**Comment by stevepiercy** [comment]
PR #5 attempts to fix incompatibility with modern Pyramid >= 1.5a2, so you can pull in that PR and try it out.

@mcdonc is not actively maintaining this package, but if someone were to volunteer to do so, then we can make it happen. Maybe @mete0r would be a good candidate because they opened PR #5?

If no one steps up, I'm tempted to remove the sidebar from the Pyramid docs. [It was written in 2010](https://github.com/Pylons/pyramid/blame/1274aba85d27d910d5aec2a775562c71e9505fdf/docs/narr/resources.rst#L175) with only a few grammar corrections since then.

**Comment by bjmc** [comment]
I agree that the sidebar should be removed from the Pyramid docs if this package isn't a viable option.

For anyone else coming across this thread, some more searching turned up [TraversalKit](https://pypi.org/project/TraversalKit/) that seems to offer similar features, and has been updated much more recently (Sept 2017).
